# --- !Ups

create table "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
  "turkerId" varchar not null,
  "loginTime" DATETIME NOT NULL);

insert into "users" ("id", "turkerId", "loginTime") values ('1','mat', '2010-01-01T13:07:02.000+01:00');

# --- !Downs

drop table "users";