# --- !Ups

create table "turkers" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
  "turkerId" varchar not null,
  "loginTime" DATETIME NOT NULL);

create table "hits" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
  "pdf" varchar not null,
  "hitReceived" DATETIME not null);

create table "questions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
  "question" varchar not null,
  "answerType" varchar not null,
  "hit_fk" BIGINT NOT NULL,
  FOREIGN KEY ("hit_fk") REFERENCES "hits"("id"));

insert into "turkers" ("id", "turkerId", "loginTime") values ('1','mat', '2014-12-24T13:07:02.000+01:00');
insert into "hits" ("id", "pdf", "hitReceived") values ('1', '00001','2014-12-26T13:07:02.000+01:00');
insert into "questions" ("id", "question", "answerType", "hit_fk") values ('1','What size of shoes?', 'number', '1');
insert into "questions" ("id", "question", "answerType", "hit_fk") values ('2','How hight are you?', 'number', '1');

# --- !Downs

drop table "turkers";
drop table "hits";
drop table "questions";