# --- !Ups

create table "turkers" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
  "turkerId" varchar not null,
  "loginTime" DATETIME NOT NULL);

create table "hits" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
  "pdf" varchar not null,
  "hitReceived" DATETIME not null);

create table "questions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
  "question" varchar not null,
  "answerType" varchar not null,
  "hit_fk" BIGINT NOT NULL,
  FOREIGN KEY ("hit_fk") REFERENCES "hits"("id"));

create table "answers" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
  "answer" varchar,
  "answerTime" DATETIME not null,
  "turkerId" BIGINT NOT NULL,
  "qId" BIGINT NOT NULL,
  FOREIGN KEY ("qId") REFERENCES "questions"("id"),
  FOREIGN KEY ("turkerId") REFERENCES "turkers"("id"));

insert into "turkers" ("id", "turkerId", "loginTime") values ('1','mat', '2014-12-24T13:07:02.000+01:00');
insert into "hits" ("id", "pdf", "hitReceived") values ('1', '00001','2014-12-26T13:07:02.000+01:00');
insert into "questions" ("id", "question", "answerType", "hit_fk") values ('1','What size of shoes?', 'number', '1');
insert into "questions" ("id", "question", "answerType", "hit_fk") values ('2','How many fingers do you have?', 'number', '1');

insert into "answers" ("id", "answer", "answerTime", "turkerId", "qId") values ('1','43', '2015-04-01T12:01:00.000+01:00', '1', '1');
insert into "answers" ("id", "answer", "answerTime", "turkerId", "qId") values ('2','42', '2015-04-01T12:12:00.000+01:00', '1', '1');
insert into "answers" ("id", "answer", "answerTime", "turkerId", "qId") values ('3','42', '2015-04-01T12:42:00.000+01:00', '1', '1');

insert into "answers" ("id", "answer", "answerTime", "turkerId", "qId") values ('4','5', '2015-04-01T12:06:20.000+01:00', '1', '2');
insert into "answers" ("id", "answer", "answerTime", "turkerId", "qId") values ('5','10', '2015-04-01T12:15:00.000+01:00', '1', '2');

# --- !Downs

drop table "turkers";
drop table "hits";
drop table "questions";
drop table "answers";